install.packages("ggplot2")
library(ggplot2)

pca_file = readline(prompt = "Enter file name for pca with extension: ")
demo = read.csv(pca_file)
colnames(demo) <- c("x","y","Disease")
qplot(x, y, col = Disease, data=demo, xlab = "x", ylab = "y", main = pca_file)

tsne_file = readline(prompt = "Enter file name for tsne with extension: ")
tsne_demo = read.csv(tsne_file)
colnames(tsne_demo) <- c("x","y","Disease")
qplot(x, y, col = Disease, data=tsne_demo, xlab = "x", ylab = "y", main = tsne_file)

svd_file = readline(prompt = "Enter file name for svd with extension: ")
svd_demo = read.csv(svd_file)
colnames(svd_demo) <- c("x","y","Disease")
qplot(x, y, col = Disease, data=svd_demo, xlab = "x", ylab = "y", main = svd_file )

# pca_a = read.csv("a.csv")
# pca_b = read.csv("b.csv")
# pca_c = read.csv("c.csv")
# tsne_a = read.csv("tsne_a.csv")
# tsne_b = read.csv("tsne_b.csv")
# tsne_c = read.csv("tsne_c.csv")
# svd_a = read.csv("svd_a.csv")
# svd_b = read.csv("svd_b.csv")
# svd_c = read.csv("svd_c.csv")
# colnames(pca_a) <- c("x","y","Disease")
# colnames(pca_b) <- c("x","y","Disease")
# colnames(pca_c) <- c("x","y","Disease")
# colnames(tsne_a) <- c("x","y","Disease")
# colnames(tsne_b) <- c("x","y","Disease")
# colnames(tsne_c) <- c("x","y","Disease")
# colnames(svd_a) <- c("x","y","Disease")
# colnames(svd_b) <- c("x","y","Disease")
# colnames(svd_c) <- c("x","y","Disease")
# qplot(x, y, col = Disease, data=pca_a, xlab = "x", ylab = "y", main = "PCA_A")
# qplot(x, y, col = Disease, data=pca_b, xlab = "x", ylab = "y", main = "PCA_B")
# qplot(x, y, col = Disease, data=pca_c, xlab = "x", ylab = "y", main = "PCA_C")
# qplot(x, y, col = Disease, data=tsne_a, xlab = "x", ylab = "y", main = "TSNE_A")
# qplot(x, y, col = Disease, data=tsne_b, xlab = "x", ylab = "y", main = "TSNE_B")
# qplot(x, y, col = Disease, data=tsne_c, xlab = "x", ylab = "y", main = "TSNE_C")
# qplot(x, y, col = Disease, data=svd_a, xlab = "x", ylab = "y", main = "SVD_A")
# qplot(x, y, col = Disease, data=svd_b, xlab = "x", ylab = "y", main = "SVD_B")
# qplot(x, y, col = Disease, data=svd_c, xlab = "x", ylab = "y", main = "SVD_C")
