install.packages("ggplot2")
library(ggplot2)
setwd("/Users/harilsatra/Documents/Sem 3/Data  Mining/Project 1")
pca_a = read.csv("a.csv")
pca_b = read.csv("b.csv")
pca_c = read.csv("c.csv")
tsne_a = read.csv("tsne_a.csv")
tsne_b = read.csv("tsne_b.csv")
tsne_c = read.csv("tsne_c.csv")
colnames(pca_a) <- c("x","y","Disease")
colnames(pca_b) <- c("x","y","Disease")
colnames(pca_c) <- c("x","y","Disease")
colnames(tsne_a) <- c("x","y","Disease")
colnames(tsne_b) <- c("x","y","Disease")
colnames(tsne_c) <- c("x","y","Disease")
#qplot(x, y, col = Disease, data=pca_a, xlab = "x", ylab = "y", main = "PCA_A")
#qplot(x, y, col = Disease, data=pca_b, xlab = "x", ylab = "y", main = "PCA_B")
#qplot(x, y, col = Disease, data=pca_c, xlab = "x", ylab = "y", main = "PCA_C")
#qplot(x, y, col = Disease, data=tsne_a, xlab = "x", ylab = "y", main = "TSNE_A")
#qplot(x, y, col = Disease, data=tsne_b, xlab = "x", ylab = "y", main = "TSNE_B")
qplot(x, y, col = Disease, data=tsne_c, xlab = "x", ylab = "y", main = "TSNE_C")
